### ISSUE TITLE
Keeps working until there is an audio in the card.

### ISSUE THREAD

**Issue by Gaphnix** [kelciour/awesometts-anki-addon#39]
Hi, 
It used to work perfectly even on that version but I don't know what happened. It still works fine while reviewing cards (Highlighting the word and right clicking then speak ) until a card with an audio in it (like prerecorded in extra field for ex.) then it stops working and gives this error.
*No new addons were added or removed*

"Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.28 (7d8818f8) Python 3.8.0 Qt 5.15.0 PyQt 5.15.0
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-08-14 23:55:40

Caught exception:
Traceback (most recent call last):
  File "aqt\mpv.py", line 349, in _get_response
  File "queue.py", line 178, in get
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aqt\mpv.py", line 376, in _send_request
  File "aqt\mpv.py", line 353, in _get_response
aqt.mpv.MPVTimeoutError: unable to get response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aqt\mpv.py", line 349, in _get_response
  File "queue.py", line 178, in get
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aqt\webview.py", line 482, in handler
  File "aqt\reviewer.py", line 320, in _onAnswerButton
  File "aqt\reviewer.py", line 261, in _answerCard
  File "aqt\reviewer.py", line 118, in nextCard
  File "aqt\reviewer.py", line 186, in _showQuestion
  File "aqt\sound.py", line 100, in play_tags
  File "aqt\sound.py", line 111, in clear_queue_and_maybe_interrupt
  File "aqt\sound.py", line 135, in _stop_if_playing
  File "aqt\sound.py", line 355, in stop
  File "aqt\mpv.py", line 605, in command
  File "aqt\mpv.py", line 383, in _send_request
  File "aqt\mpv.py", line 376, in _send_request
  File "aqt\mpv.py", line 353, in _get_response
aqt.mpv.MPVTimeoutError: unable to get response"

**Comment by kelciour** [comment]
Hi,

At first, if it's possible, try to update to Anki 2.1.30 and let me know if you will be still getting this error.
