### ISSUE TITLE
RuntimeError: wrapped C/C++ object of type Browser has been deleted

### ISSUE THREAD

**Issue by KungManKit** [kelciour/awesometts-anki-addon#41]
Unclear how to trigger. Usually happens after adding a few cards.

`Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-10-16 21:05:52

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 37, in cmd
  File "aqt\webview.py", line 123, in _onCmd
  File "aqt\webview.py", line 547, in _onBridgeCmd
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-22>", line 2, in onBridgeCmd
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 635, in repl
  File "C:\Users\Kung Man Kit\AppData\Roaming\Anki2\addons21\516643804\main.py", line 135, in onBridge
    return _old(self, str)
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-6>", line 2, in onBridgeCmd
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 635, in repl
  File "C:\Users\Kung Man Kit\AppData\Roaming\Anki2\addons21\1463041493\main.py", line 341, in onBridgeCmd
    return _old(ed, cmd)
  File "aqt\editor.py", line 418, in onBridgeCmd
  File "C:\Users\Kung Man Kit\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\common.py", line 121, in _show
    self._instance = self._target.constructor(
  File "C:\Users\Kung Man Kit\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\generator.py", line 670, in __init__
    super(EditorGenerator, self).__init__(
  File "C:\Users\Kung Man Kit\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 243, in __init__
    super(ServiceDialog, self).__init__(*args, **kwargs)
  File "C:\Users\Kung Man Kit\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 77, in __init__
    super(Dialog, self).__init__(parent)
RuntimeError: wrapped C/C++ object of type Browser has been deleted`

**Comment by kelciour** [comment]
Thank you for the report. At the moment, I can only suggest either to install https://ankiweb.net/shared/info/1436550454 as the same error should be already fixed in it, as far as I know, or use the add-on from the card browser to batch generate audio files https://ankiatts.appspot.com/usage/browser.

I tried to fix it a while ago but couldn't figure out how to do it but I'll try to do it again once I'm not too busy, maybe this month.
