### ISSUE TITLE
Crashes if you open "Browse"

### ISSUE THREAD

**Issue by cpolocze** [kelciour/awesometts-anki-addon#44]
If you open "Browse" while you are adding new cards to a deck, the add-on will automatically target a field from a card in the browse window, even if the text cursor is set to a field in the "add cards" window. If you close the browse window, the add-one crashes when you try to open it in the add window.

<details>
  <summary>Error message</summary>
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-10-29 22:07:27

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 37, in cmd
  File "aqt\webview.py", line 123, in _onCmd
  File "aqt\webview.py", line 547, in _onBridgeCmd
  File "aqt\editor.py", line 418, in onBridgeCmd
  File "C:\Users\Christopher\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\common.py", line 121, in _show
    self._instance = self._target.constructor(
  File "C:\Users\Christopher\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\generator.py", line 670, in __init__
    super(EditorGenerator, self).__init__(
  File "C:\Users\Christopher\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 243, in __init__
    super(ServiceDialog, self).__init__(*args, **kwargs)
  File "C:\Users\Christopher\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 77, in __init__
    super(Dialog, self).__init__(parent)
RuntimeError: wrapped C/C++ object of type Browser has been deleted

  
  
</details>

**Comment by kelciour** [comment]
Thank you very much for the issue and the exact steps on how to reproduce it. It was reported a few times before but without much information how to trigger it. I really appreciate it.

I reproduced it a while ago and tried to fix it but failed to do so in a short amount of time. It's something I'd like to fix, but it might take some time, at least a few weeks, before I'll try to do it again.

For now, either maybe batch generate from the card browser or install https://ankiweb.net/shared/info/1436550454 as it should be already fixed there, as far as I know.
