### ISSUE TITLE
Error AwesomeTTS (Google Cloud Text-to-Speech & Microsoft Azure TTS)

### ISSUE THREAD

**Issue by luizengmec** [kelciour/awesometts-anki-addon#60]
Erro
Ocorreu um erro. Por favor, inicie o Anki enquanto segura a tecla shift, isto vai desabilitar temporariamente as extensões que você instalou.
Se o problema ocorrer somente quando as extensões são habilitadas, use o Ferramentas > Extensões para desabilitar algumas extensões e reinicie o Anki, repetindo até descobrir a extensão que está causando o problema.
Quando você descobrir a extensão que está causando o problema, por favor reporte o problema em site de suporte de extensão.
Informações de Depuração:
Anki 2.1.52 (ab1c2395) Python 3.9.7 Qt 6.3.0 PyQt 6.3.0
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-05-18 15:37:28

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 42, in cmd
  File "aqt.webview", line 149, in _onCmd
  File "aqt.webview", line 619, in _onBridgeCmd
  File "aqt.editor", line 464, in onBridgeCmd
  File "C:\Users\luizi\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\common.py", line 121, in _show
    self._instance = self._target.constructor(
  File "C:\Users\luizi\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\generator.py", line 670, in __init__
    super(EditorGenerator, self).__init__(
  File "C:\Users\luizi\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 243, in __init__
    super(ServiceDialog, self).__init__(*args, **kwargs)
  File "C:\Users\luizi\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 80, in __init__
    self.setLayout(self._ui())
  File "C:\Users\luizi\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 255, in _ui
    hor.addLayout(self._ui_services())
  File "C:\Users\luizi\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 313, in _ui_services
    layout.addLayout(self._ui_services_presets())
  File "C:\Users\luizi\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 340, in _ui_services_presets
    save.setFixedWidth(save.fontMetrics().width(save.text()) + 20)
AttributeError: 'QFontMetrics' object has no attribute 'width'

**Comment by nickycyee** [comment]
same issue:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-07-10 14:15:10

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 42, in cmd
  File "aqt.webview", line 149, in _onCmd
  File "aqt.webview", line 624, in _onBridgeCmd
  File "aqt.editor", line 467, in onBridgeCmd
  File "C:\Users\Nicky\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\common.py", line 121, in _show
    self._instance = self._target.constructor(
  File "C:\Users\Nicky\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\generator.py", line 670, in __init__
    super(EditorGenerator, self).__init__(
  File "C:\Users\Nicky\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 243, in __init__
    super(ServiceDialog, self).__init__(*args, **kwargs)
  File "C:\Users\Nicky\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 80, in __init__
    self.setLayout(self._ui())
  File "C:\Users\Nicky\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 255, in _ui
    hor.addLayout(self._ui_services())
  File "C:\Users\Nicky\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 313, in _ui_services
    layout.addLayout(self._ui_services_presets())
  File "C:\Users\Nicky\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 340, in _ui_services_presets
    save.setFixedWidth(save.fontMetrics().width(save.text()) + 20)
AttributeError: 'QFontMetrics' object has no attribute 'width'
