### ISSUE TITLE
Error in AwesomeTTS in my Anki, help me please.

### ISSUE THREAD

**Issue by pedroevangelista** [kelciour/awesometts-anki-addon#62]
Erro
Ocorreu um erro. Por favor, inicie o Anki enquanto segura a tecla shift, isto vai desabilitar temporariamente as extensões que você instalou.
Se o problema ocorrer somente quando as extensões são habilitadas, use o Ferramentas > Extensões para desabilitar algumas extensões e reinicie o Anki, repetindo até descobrir a extensão que está causando o problema.
Quando você descobrir a extensão que está causando o problema, por favor reporte o problema em site de suporte de extensão.
Informações de Depuração:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-09-05 07:50:11

Caught exception:
Traceback (most recent call last):
  File "C:\Users\pedro\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\common.py", line 121, in _show
    self._instance = self._target.constructor(
  File "C:\Users\pedro\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\configurator.py", line 76, in __init__
    super(Configurator, self).__init__(title="Configuration",
  File "C:\Users\pedro\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 80, in __init__
    self.setLayout(self._ui())
  File "C:\Users\pedro\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\configurator.py", line 85, in _ui
    layout.addWidget(self._ui_tabs())
  File "C:\Users\pedro\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\configurator.py", line 103, in _ui_tabs
    tabs.addTab(content(), QtGui.QIcon(f'{ICONS}/{icon}.png'),
  File "C:\Users\pedro\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\configurator.py", line 189, in _ui_tabs_text
    layout.addWidget(self._ui_tabs_text_mode(
  File "C:\Users\pedro\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\configurator.py", line 223, in _ui_tabs_text_mode
    ("Advanced", self._ui_tabs_text_mode_adv(infix)),
  File "C:\Users\pedro\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\configurator.py", line 338, in _ui_tabs_text_mode_adv
    return Slate("Rule", SubListView, [self._sul_compiler],
  File "C:\Users\pedro\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\common.py", line 359, in __init__
    list_view = ListViewClass(*list_view_args)
  File "C:\Users\pedro\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\listviews.py", line 115, in __init__
    super(SubListView, self).__init__(*args, **kwargs)
  File "C:\Users\pedro\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\listviews.py", line 50, in __init__
    self.setSelectionMode(self.ExtendedSelection)
AttributeError: 'SubListView' object has no attribute 'ExtendedSelection'

**Comment by nelsonveras** [comment]
Boa noite. Estou tendo o mesmo problema. E estou há duas horas no Anki e na internet tentando descobrir solução.

**Comment by kelciour** [comment]
The add-on needs to be updated to work with Qt6. Instead, either try it with Anki Qt5, but it might be buggy too, or uninstall it and install AwesomeTTS - Add speech to your flashcards - https://ankiweb.net/shared/info/1436550454

**Comment by nelsonveras** [comment]
Obrigado, @kelciour . Consegui resolver o problema.
