### ISSUE TITLE
Hi. How can I fix it :'QFontMetrics' object has no attribute 'width'

### ISSUE THREAD

**Issue by sinahgh** [kelciour/awesometts-anki-addon#64]
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-11-23 16:31:32

Caught exception:
Traceback (most recent call last):
  File "C:\Users\s.haghani.PDD0\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\common.py", line 121, in _show
    self._instance = self._target.constructor(
  File "C:\Users\s.haghani.PDD0\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\generator.py", line 59, in __init__
    super(BrowserGenerator, self).__init__(
  File "C:\Users\s.haghani.PDD0\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 243, in __init__
    super(ServiceDialog, self).__init__(*args, **kwargs)
  File "C:\Users\s.haghani.PDD0\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 80, in __init__
    self.setLayout(self._ui())
  File "C:\Users\s.haghani.PDD0\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 255, in _ui
    hor.addLayout(self._ui_services())
  File "C:\Users\s.haghani.PDD0\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 313, in _ui_services
    layout.addLayout(self._ui_services_presets())
  File "C:\Users\s.haghani.PDD0\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 340, in _ui_services_presets
    save.setFixedWidth(save.fontMetrics().width(save.text()) + 20)
AttributeError: 'QFontMetrics' object has no attribute 'width'

**Comment by kelciour** [comment]
For now either by installing Anki 2.1.54 **Qt5** or AwesomeTTS - Add speech to your flashcards - https://ankiweb.net/shared/info/1436550454
