### ISSUE TITLE
AwesomeTTS Anki add-on, Bugs help

### ISSUE THREAD

**Issue by jurajsolarml** [kelciour/awesometts-anki-addon#66]
Hello, 
Please help. clicking on the speaker icon writes an error in Anki. Thanks

Best Wishes

Juraj Solár ml.

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.61 (0c1eaf4c) Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
Platform: Windows-10-10.0.19044
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-04-03 17:12:48

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 46, in cmd
  File "aqt.webview", line 153, in _onCmd
  File "aqt.webview", line 662, in _onBridgeCmd
  File "aqt.editor", line 474, in onBridgeCmd
  File "C:\Users\juraj\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\common.py", line 121, in _show
    self._instance = self._target.constructor(
  File "C:\Users\juraj\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\generator.py", line 670, in __init__
    super(EditorGenerator, self).__init__(
  File "C:\Users\juraj\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 243, in __init__
    super(ServiceDialog, self).__init__(*args, **kwargs)
  File "C:\Users\juraj\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 80, in __init__
    self.setLayout(self._ui())
  File "C:\Users\juraj\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 255, in _ui
    hor.addLayout(self._ui_services())
  File "C:\Users\juraj\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 313, in _ui_services
    layout.addLayout(self._ui_services_presets())
  File "C:\Users\juraj\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 340, in _ui_services_presets
    save.setFixedWidth(save.fontMetrics().width(save.text()) + 20)
AttributeError: 'QFontMetrics' object has no attribute 'width'

**Comment by kelciour** [comment]
It's been a while since the add-on was last updated.  At the moment, it could be fixed either by installing AwesomeTTS - Add speech to your flashcards - https://ankiweb.net/shared/info/1436550454 - or by installing Qt5 version of Anki but some improvements will be lost.

> Advantages of the Qt6 version:
> - Various bugfixes, including things like better support for less common languages.
> - Very large images load faster than the Qt5 version.
>
> https://docs.ankiweb.net/platform/windows/installing.html#qt5-vs-qt6

**Comment by jurajsolarml** [comment]
Ok, Thanks
